VALORES_DEPARTAMENTO= [
'AMAZONAS',
'ANTIOQUIA',
'ANTIOQUIA',
'ANTIOQUIA',
'ARAUCA',
'ARAUCA',
'ATLANTICO',
'BOGOTA',
'BOLIVAR',
'BOYACA',
'BOYACA',
'CALDAS',
'CAQUETA',
'CASANARE',
'CAUCA',
'CESAR',
'CHOCO',
'CORDOBA',
'CUNDINAMARCA',
'GUAINIA',
'GUAVIARE',
'HUILA',
'LA GUAJIRA',
'MAGDALENA',
'META',
'NARINO',
'NORTE DE SANTANDER',
'POR DETERMINAR',
'PUTUMAYO',
'PUTUMAYO',
'QUINDIO',
'QUINDIO',
'RISARALDA',
'SAN ANDRES Y PROVIDENCIA',
'SANTANDER',
'SUCRE',
'TOLIMA',
'VALLE DEL CAUCA',
'VICHADA',
]

VALORES_REEMPLAZO_DEPARTAMENTO = {
    # Reemplazos de Guajira
    "GUAJIRA": "LA GUAJIRA",
    
    # Reemplazos de Norte de Santander
    "N.SANTANDER": "NORTE DE SANTANDER",
    "NORTE SANTANDER": "NORTE DE SANTANDER",
    "NSANTANDER": "NORTE DE SANTANDER",
    
    # Reemplazos de Valle del Cauca
    "VALLE": "VALLE DEL CAUCA",
    
    # Reemplazos de San Andrés y Providencia
    "SAN_ANDRES_Y_PROVIDENCIA": "SAN ANDRES Y PROVIDENCIA",
    "SAN ANDRES": "SAN ANDRES Y PROVIDENCIA",
    
    # Reemplazos de Bogotá D.C.
    "BOGOTA DC": "BOGOTA",
    "BOGOTA D.C.": "BOGOTA",
    "BOGOTÁ D.C.": "BOGOTA",
    "BOGOTÁ DC": "BOGOTA",
    "BOGOTÁ D C": "BOGOTA",
    "BOGOTÁ DISTRITO CAPITAL": "BOGOTA",
    "DISTRITO CAPITAL": "BOGOTA",
    "D.C.": "BOGOTA",
    "DC": "BOGOTA",
    "BOGOTÁ": "BOGOTA",
    
    # Reemplazos de Cundinamarca
    "CUNDINAMRCA": "CUNDINAMARCA",
    "CUNDINAMCA": "CUNDINAMARCA",
    "CUNDINAMRACA": "CUNDINAMARCA",
    "CUNDINAMARCA": "CUNDINAMARCA",  # Para casos donde ya está correcto
}